name: Release sample-container-todo-app-java-gradle to Docker Hub

on:
  workflow_dispatch:

jobs:
  docker:
    name: Publish - Docker Hub
    runs-on: ubuntu-latest
    env:
      REPO: tolgatakir/sample-container-todo-app-java-gradle

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'adopt'
          cache: 'gradle'
      - name: Create artifact
        run: ./gradlew build -x test
      - name: Login to Docker Hub
        run: docker login -u tolgatakir -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Build Docker image
        run: docker build -t $REPO:latest -t $REPO:${GITHUB_SHA::8} .
      - name: Publish Docker image
        run: docker push $REPO -a
